"""add analysis table

Revision ID: 0002
Revises: 0001
Create Date: 2023-06-27 11:46:55.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('best_move', sa.String(), nullable=True),
    sa.Column('pv', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_moves', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_fen'), 'analyses', ['fen'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_fen'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
